Repository iml1111/trAIner, pull requests merged in 2022-11, with the labels that each got.

#7 [feat-cf] CF 기반 Deep Model 학습 구현 완료
  Recommenders/deepfm/train.py
  Recommenders/deepfm/trainer.py
Labels: enhancement

#14 [feat-13] 도커라이징 및 자동화
  .github/workflows/deploy_prod.yml
  trAIner/Dockerfile
  trAIner/config.py
  trAIner/requirements.txt
Labels: enhancement

#16 [feat-8] Deep Model Predictor Controller 구현
  Recommenders/deepfm/predict.py
  trAIner/config.py
  trAIner/controller/deep_predictor.py
  trAIner/requirements.txt
Labels: enhancement

#20 [feat-11] Topic Model Predict Controller 구현
  .gitignore
  Recommenders/fasttext/data_loader.py
  Recommenders/fasttext/ft_model_v1
  Recommenders/fasttext/train.py
  Recommenders/fasttext/trainer.py
  Recommenders/fasttext/word_sim_test.md
  trAIner/config.py
  trAIner/controller/topic_predictor.py
  trAIner/requirements.txt
Labels: enhancement

#21 [feat-19] 외부 python 스크립트 실행 controller 구현
  trAIner/controller/python_executor.py
Labels: enhancement

#23 [feat-22] Admin Interface 파라미터 get/set API 구현
  trAIner/app/api/v1/__init__.py
  trAIner/app/api/v1/admin.py
  trAIner/controller/deep_predictor.py
  trAIner/model/mongodb/master_config.py
Labels: enhancement

#24 [feat-18] Problem APIs 구현
  .github/workflows/deploy_prod.yml
  trAIner/app/__init__.py
  trAIner/app/api/__init__.py
  trAIner/app/api/auth.py
  trAIner/app/api/decorator.py
  trAIner/app/api/response.py
  trAIner/app/api/v1/__init__.py
  trAIner/app/api/v1/problem.py
  trAIner/app/api/v1/user.py
  trAIner/config.py
  trAIner/controller/hot_problem.py
  trAIner/controller/topic_predictor.py
  trAIner/controller/util.py
  trAIner/model/mongodb/__init__.py
  trAIner/model/mongodb/interact.py
  trAIner/model/mongodb/problem.py
  trAIner/model/mongodb/roadmap.py
  trAIner/model/mongodb/solve_log.py
  trAIner/model/mongodb/user.py
  trAIner/requirements.txt
Labels: enhancement

#29 [feat-28] cold APIs 구현 및 피드백 반영
  trAIner/app/api/auth.py
  trAIner/app/api/v1/problem.py
  trAIner/controller/cold_problem.py
  trAIner/controller/hot_problem.py
  trAIner/controller/tag.py
  trAIner/controller/util.py
  trAIner/model/mongodb/interact.py
  trAIner/model/mongodb/master_config.py
  trAIner/model/mongodb/problem.py
  trAIner/model/mongodb/solve_log.py
Labels: enhancement

#32 [feat-31] 제출/채점 API 구현
  trAIner/app/api/v1/admin.py
  trAIner/app/api/v1/problem.py
  trAIner/controller/cold_problem.py
  trAIner/controller/python_executor.py
  trAIner/model/mongodb/problem.py
  trAIner/model/mongodb/solve_log.py
  trAIner/model/mongodb/user.py
Labels: enhancement

#35 [bugfix-34] 콜드 유저, 핫 유저 목록 반환 400으로 예외처리
  trAIner/app/api/v1/problem.py
  trAIner/controller/cold_problem.py
  trAIner/controller/python_executor.py
  trAIner/model/mongodb/solve_log.py
  trAIner/model/mongodb/user.py
Labels: bug, enhancement

#40 [refac-39] 틀릴 가능성이 높은 문제 반환 속도 개선
  trAIner/controller/deep_predictor.py
  trAIner/controller/hot_problem.py
Labels: refac
